# This is a basic workflow that is manually triggered

name: autorun workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 */8 * * *'
  push:
    branches:
      - main



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ss"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
     GIST_PAT: ${{ vars.GIST_PAT }}
     GIST_LINK: ${{ vars.GIST_LINK }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code  # 检出代码
      uses: actions/checkout@v3

    - name: Set up Python  # 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # 指定Python版本
    - name: 安装依赖
      run: pip install -r requirements.txt
    - name: 节点获取并发布
      run: | 
        python test.py
       
    - name: Commit and push output file
      run: |
        git config --local user.email "186155633@qq.com"  # 替换为你的 GitHub 注册邮箱
        git config --local user.name "akflytiger"  # 替换为你的 GitHub 用户名
        git add hk.yaml  # 将生成的 output.txt 文件添加到暂存区，注意文件名要和代码中保存的一致
        git commit -m "sstoclash_config_auto.yaml"  # 提交更改，提交信息可自定义
        git push origin HEAD --force  # 将更改推送到当前分支，确保你的仓库有对应权限配置
